

spring:
  redis:
    lettuce:
      pool:
        #连接池最大连接数 使用负值代表无限制 默认为8
        max-active: 10
        #最大空闲连接 默认8
        max-idle: 10
        #最小空闲连接 默认0
        min-idle: 1
#    host: 127.0.0.1
    host: 192.168.15.129
#    password: 12345
    port: 6381
    database: 2
    timeout: 2000ms




server:
  port: 8086
