#server:
#  port: 8066
#spring:
#  elasticsearch:
#    rest:
#      uris: localhost:9200

## ElasticSearch 配置
elasticsearch:
  schema: http
  address: localhost:9200
  connectTimeout: 10000
  socketTimeout: 15000
  connectionRequestTimeout: 20000
  maxConnectNum: 100
  maxConnectPerRoute: 100
  index: "aha"


