#配置端口
server:
  port: 8080

spring:
  #配置数据源
  datasource:
    #配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    #配置连接数据库的信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_learn?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

#MyBatis-Plus相关配置
mybatis-plus:
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 设置实体类所对应的表的统一前缀
      table-prefix: t_
      #配置mp的主键策略
      id-type: auto
  mapper-locations: classpath:mybatisplus/mapper/*.xml
  # 扫描通用枚举的包
  type-enums-package: com.wxj.springboot.mybatisplus.enums