server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot_learn?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver # 注意：如果你的mysql的jar包引入的是8.0以上版本，则驱动为：com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 # 初始化时建立物理连接的个数
      min-idle: 5 # 最小连接池数量
      max-active: 100 # 最大连接池数量
      max-wait: 60000 # 获取连接时最大等待时间
      stat-view-servlet:
        login-username: admin # 配置监控页面访问登录名称
        login-password: admin # 配置监控页面访问密码
      filter:
        stat:
          log-slow-sql: true # 是否开启慢sql查询监控
          slow-sql-millis: 1 # 慢SQL执行时间
      pool-prepared-statements: true
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-open-prepared-statements: 20
      validation-query: SELECT 1 FROM DUAL

  application:
    name: mybatis-plus-demo

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰法则
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 放开则开启SQL打印（就是每次SQL操作数据库都会在控制台打印出来，建议使用熟练以后关闭，不然日志很多）
  type-aliases-package: com.taoge.po # 实体类包路径
  mapper-locations: classpath*:mapper/**/*Mapper.xml # 存放sql语句的xml文件目录
  global-config:
    db-config:
      logic-delete-field: delFlag # 全局逻辑删除的实体字段名（这里填表字段名好像也可以）
      logic-delete-value: 1 # 逻辑已删除值（为1，表示已删除）
      logic-not-delete-value: 0 # 逻辑未删除值(默认为0, 表示未删除)

# 分页插件PageHelper配置
pagehelper:
  helper-dialect: mysql
  pageSizeZero: true
  params: count=countSql
  reasonable: true
  support-methods-arguments: true



#
## 配置端口
#server:
#  port: 8085
#  servlet:
#    context-path: /test
#    application-display-name: mybatis-plus-demo
#
#spring:
#  application:
#    name: mybatis-plus-demo
#  # 配置数据源
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/springboot_learn?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#    druid:
#      filters: stat
#      maxActive: 20
#      initialSize: 1
#      maxWait: 60000
#      minIdle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select '1'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20
#
## mybatis-plus相关配置
#mybatis-plus:
#  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
#  mapper-locations: classpath:**/*Mapper.xml
#  # 以下配置均有默认值,可以不设置
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: false
#    #数据库大写下划线转换
#    #capital-mode: true
#    #序列接口实现类配置
#    #key-generator: com.baomidou.springboot.xxx
#    #逻辑删除配置
#    #logic-delete-value: 0 # 逻辑已删除值(默认为 1)
#    #logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
#    #自定义填充策略接口实现
#    #    meta-object-handler: com.zhengqing.config.MyMetaObjectHandler
#    #自定义SQL注入器
#    #sql-injector: com.baomidou.springboot.xxx
#  configuration:
#    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
#    #    call-setters-on-nulls: true
#    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    # 解决oracle更新数据为null时无法转换报错，mysql不会出现此情况
#    jdbc-type-for-null: 'null'